<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-G2HPLVO2" failures="1" tests="7" name="com.Thue.com.Thue.ThueTest" time="0.019" errors="0" timestamp="2022-03-28T13:42:05 ICT" skipped="0">
  <testcase classname="com.Thue.com.Thue.ThueTest" name="ThueMyTest20" time="0.002"/>
  <system-out/>
  <testcase classname="com.Thue.com.Thue.ThueTest" name="ThueMyTest15" time="0.002"/>
  <system-out/>
  <testcase classname="com.Thue.com.Thue.ThueTest" name="ThueMyTest25" time="0.000"/>
  <system-out/>
  <testcase classname="com.Thue.com.Thue.ThueTest" name="ThueMyTest5" time="0.004">
    <failure message="expected [4.0] but found [1.4]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [4.0] but found [1.4]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:701)
at org.testng.Assert.assertEquals(Assert.java:712)
at com.Thue.com.Thue.ThueTest.ThueMyTest5(ThueTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ThueMyTest5 -->
  <system-out/>
  <testcase classname="com.Thue.com.Thue.ThueTest" name="ThueMyTest10" time="0.008"/>
  <system-out/>
  <testcase classname="com.Thue.com.Thue.ThueTest" name="ThueMyTest30" time="0.001"/>
  <system-out/>
  <testcase classname="com.Thue.com.Thue.ThueTest" name="ThueMyTest35" time="0.002"/>
  <system-out/>
</testsuite> <!-- com.Thue.com.Thue.ThueTest -->
